#!/bin/bash
if [[ $(whoami) != "root" ]]; then
    echo "sudo !!"
    exit
fi

dir=$1
if [[ "$dir" == "up" ]]; then
    value="performance"
elif [[ "$dir" == "down" ]]; then
    value="powersave"
elif [[ "$dir" == "half" ]]; then
    value="half"
elif [[ "$dir" == "cat" ]]; then
    value="cat"
else
    echo "input has to be 'up', 'down', 'half', or 'cat'"
    exit 1
fi

cd /sys/devices/system/cpu/cpufreq/ || exit 1

count=0
for i in */scaling_governor; do
    ((count++))
    prev=$(cat $i)

    if [[ $value == "cat" ]]; then
        echo "$prev"
        continue
    fi

    if [[ $value == "half" ]]; then
        if [[ $((count % 2)) -eq 1 ]]; then
            write_value="performance"
        else
            write_value="powersave"
        fi
    else
        write_value="$value"
    fi

    echo $write_value >$i
    curr=$(cat $i)
    echo "$i: $prev -> $curr"
done
