#!/usr/bin/env python
import sys
import json
from pathlib import Path

from bs4 import BeautifulSoup as BS

def output_json(fpath):
    with open(fpath) as f:
        obj = json.load(f)
    print(json.dumps(obj, indent=4))


def output_html(fpath):
    with open(fpath) as f:
        text = f.read()
    print(BS(text, 'html.parser').prettify())


def main(fname):
    fpath = Path(fname)
    ext = fpath.suffix

    with open(fpath) as f:
        text = f.read(4096)
    firstline = text.split('\n')[0]

    if ext == '.json':
        output_json(fpath)
    elif ext == '.html' or ext == '.htm' or 'html' in firstline.lower():
        output_html(fpath)

    else:
        raise NotImplementedError(f"unsupported file extension: '{ext}'")

if __name__ == '__main__':
    try:
        main(sys.argv[1])
    except IndexError:
        print(f'ERROR: no file specified', file=sys.stderr)

